import requests
import random
import os
import json
import time
from datetime import datetime

# CONFIG: Change these seeds to match your niche!
SEEDS = [
    "how to fix android",
    "roblox error code",
    "call of duty mobile lag",
    "whatsapp not sending",
    "best graphics settings for",
    "iphone battery draining fast"
]

def get_gemini_article(title):
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        print("❌ No API Key found!")
        return None
        
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key={api_key}"
    
    # We ask for HTML directly so we don't have to format it manually
    prompt = f"""
    Write a blog post titled '{title}'. 
    Format it in valid HTML (use <h2>, <p>, <ul>). 
    Do not use <html> or <body> tags, just the content. 
    Keep it under 600 words. 
    Tone: Helpful, technical, and clear.
    """
    
    payload = {"contents": [{"parts": [{"text": prompt}]}]}
    headers = {"Content-Type": "application/json"}
    
    try:
        r = requests.post(url, json=payload, headers=headers)
        data = r.json()
        return data['candidates'][0]['content']['parts'][0]['text']
    except Exception as e:
        print(f"❌ Gemini Error: {e}")
        return None

def update_homepage(filename, title):
    # If index.html doesn't exist, create it
    if not os.path.exists("index.html"):
        with open("index.html", "w") as f:
            f.write("<html><head><title>Tech Fix Daily</title></head><body><h1>Daily Tech Fixes</h1><ul></ul></body></html>")
            
    # Read existing content
    with open("index.html", "r") as f:
        content = f.read()
        
    # Inject new link at the top of the list
    new_link = f'<li><a href="{filename}">{title}</a> ({datetime.now().strftime("%Y-%m-%d")})</li>'
    
    if "<ul>" in content:
        content = content.replace("<ul>", f"<ul>\n{new_link}")
    else:
        content = content.replace("<body>", f"<body><ul>{new_link}</ul>")
        
    with open("index.html", "w") as f:
        f.write(content)

def main():
    # 1. Pick a topic
    topic_base = random.choice(SEEDS)
    # Add a random suffix to make it unique (e.g., "in 2026", "easy fix")
    suffixes = ["2026", "easy fix", "tutorial", "solved", "guide"]
    title = f"{topic_base} {random.choice(suffixes)}".title()
    
    print(f"💀 Generating Zombie Content for: {title}")
    
    # 2. Write the Article
    article_body = get_gemini_article(title)
    
    if article_body:
        # Clean up Markdown formatting if Gemini adds it
        article_body = article_body.replace("```html", "").replace("```", "")
        
        filename = title.lower().replace(" ", "-") + ".html"
        
        # 3. Create the Page (With Space for Ads)
        full_html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>{title}</title>
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <style>
                body {{ font-family: sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; line-height: 1.6; }}
                h1 {{ color: #333; }}
                .ad-space {{ background: #eee; padding: 20px; text-align: center; margin: 20px 0; border: 1px dashed #ccc; }}
            </style>
        </head>
        <body>
            <a href="index.html">← Back to Home</a>
            
            <h1>{title}</h1>
            
            <div class="ad-space">
                <p>Sponsored Advertisement</p>
            </div>
            
            {article_body}
            
            <div class="ad-space">
                <p>Sponsored Advertisement</p>
            </div>
            
            <hr>
            <p><small>Generated by The Zombie System</small></p>
        </body>
        </html>
        """
        
        with open(filename, "w") as f:
            f.write(full_html)
            
        update_homepage(filename, title)
        print(f"🧟 Successfully birthed: {filename}")
    else:
        print("❌ Failed to generate content.")

if __name__ == "__main__":
    main()
